name: For The Sake Of Adventure
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7766763740219176
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.39302743203006685
  lightness: 0.8825285835191607
  saturation: 0.4447371317073703
  rhythmicContrast: 0.8460800400935113
purpose: []
